### ISSUE TITLE
 feat: Add ability do distinguish the explicit block on the graph #86 got lost

### ISSUE THREAD

**Issue by Geertsky** [haidaraM/ansible-playbook-grapher#223]
First of all thanks allot for this great tool! 
I think I found a bug as what I'm trying to accomplish seems to be requested before + implemented. But it got lost somehow.
I don't know in how far this feature #86 was implemented but I've just tested the blocks where I'm interested in.

**Describe the bug**
I have a playbook with blocks in different sections of the play. I'm using pre_task blocks, tasks blocks, role task blocks and imported roles with task_from a tasks file with blocks. Only the pre_tasks and task blocks seem to be working.

This could actually also be a feature request... I don't know in how far my requirements were implemented by #86, because I was unable to successful test at 77d3f2bd6aa7d1367dcf4fc6b8bef147d844b548 ...

**To Reproduce**
**playboook.yml**

```
---

- name: test
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Block of pre_tasks
      block:
        - name: Pre_task in a block
          ansible.builtin.debug:
            msg: msg from pre_task in a block
  roles:
    - role: test

  tasks:
    - name: Task with a msg
      ansible.builtin.debug:
        msg: msg from a task

    - name: Block of tasks
      block:
        - name: Task in a block
          ansible.builtin.debug:
            msg: msg from a task in a block
```

**test/tasks/main.yml**

```
---                                                                                                                       
                                                                                                                          
- name: Task with a msg in a role                                                                                         
  ansible.builtin.debug:                                                                                                  
    msg: Msg from a task                                                                                                  
                                                                                                                          
- name: Block of tasks in a role                                                                                          
  block:                                                                                                                  
    - name: Block in a role                                                                                               
      ansible.builtin.debug:                                                                                              
        msg: Msg from a task in a block in a role                                                                         
                                                                                                                          
- name: Import tasks_file                                                                                                 
  ansible.builtin.import_role:                                                                                            
    name: test                                                                                                            
    tasks_from: tasks_with_block                                 
```

**test/tasks/tasks_with_block.yml**

```
---                                                                                                                       
                                                                                                                          
- name: Task with a msg from a tasks_file of a role
  ansible.builtin.debug:
    msg: msg from a task from a tasks_file of a role

- name: Block in a tasks_file of a role
  block:
    - name: Task in a block in a tasks_file of a role
      ansible.builtin.debug:
        msg: "This is a msg from a task in a block in a tasks_file of a role"
```

**Expected behavior**
A nice graph with tasks in blocks

**Screenshots**

![playbook-test](https://github.com/user-attachments/assets/5612e474-e6e0-4e19-a67c-290d5084359d)

**Versions:**
Outputs of :
 - `ansible --version`

``` 
ansible [core 2.17.6]
  config file = ansible.cfg
  configured module search path = ['/home/geertsky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/geertsky/miniforge3/envs/ansible-2.17.6-playbook-grapher/lib/python3.13/site-packages/ansible
  ansible collection location = /home/geertsky/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/geertsky/miniforge3/envs/ansible-2.17.6-playbook-grapher/bin/ansible
  python version = 3.13.1 | packaged by conda-forge | (main, Dec  5 2024, 21:23:54) [GCC 13.3.0] (/home/geertsky/miniforge3/envs/ansible-2.17.6-playbook-grapher/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```
 - `ansible-playbook-grapher --version`

```
ansible-playbook-grapher 2.6.0 (with ansible 2.17.6)
```

**Additional context**
